version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongodb-datavolume:/data/db
volumes:
  mongodb-datavolume:
